# Generated by Django 5.2 on 2025-11-01 10:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterTradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('Asian', 'Asian'), ('London', 'London'), ('NewYork', 'New York')], max_length=20)),
                ('bias', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=10)),
                ('htf_mitigation', models.BooleanField(default=False)),
                ('liquidity_analysis', models.CharField(choices=[('buyside swept', 'Buyside Swept'), ('sellside swept', 'Sellside Swept'), ('neither', 'Neither'), ('both', 'Both'), ('london lows swept', 'London Lows Swept')], max_length=50)),
                ('market_condition', models.CharField(choices=[('Trending Up', 'Trending Up'), ('Trending Down', 'Trending Down'), ('Consolidating', 'Consolidating')], max_length=20)),
                ('lower_tf_confirmation', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10)),
                ('risk_management_applied', models.BooleanField(default=False)),
                ('high_impact_news', models.BooleanField(default=False)),
                ('major_impact_news', models.CharField(blank=True, max_length=200)),
                ('predicted_directional_bias', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partial', 'Partial')], max_length=10)),
                ('poi_performance', models.CharField(choices=[('respected perfectly', 'Respected Perfectly'), ('overshot', 'Overshot'), ('partial fill', 'Partial Fill'), ('no htf poi', 'No HTF POI'), ('rejected', 'Rejected')], max_length=20)),
                ('risk_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('market_behaviour', models.CharField(choices=[('as expected', 'As Expected'), ('choppy', 'Choppy'), ('surprise', 'Surprise'), ('opposite', 'Opposite'), ('hit stop then reversed', 'Hit Stop Then Reversed')], max_length=30)),
                ('entry_quality', models.CharField(choices=[('perfect', 'Perfect'), ('chased', 'Chased'), ('early', 'Early'), ('late', 'Late'), ('stop loss issue', 'Stop Loss Issue')], max_length=20)),
                ('poi_quality_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('time_of_entry', models.TimeField()),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], max_length=10)),
                ('is_win', models.BooleanField(default=False, editable=False)),
                ('discipline_score', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very poor', 'Very Poor')], max_length=20)),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='journal/after_trade/')),
                ('observations', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_trade_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'After Trade Entries',
                'ordering': ['-date', '-time_of_entry'],
            },
        ),
        migrations.CreateModel(
            name='BacktestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('htf_bias', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=10)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('market_condition', models.CharField(choices=[('Trending Up', 'Trending Up'), ('Trending Down', 'Trending Down'), ('Consolidating', 'Consolidating')], max_length=20)),
                ('price_within_htf_poi', models.BooleanField(default=False)),
                ('liquidity_analysis', models.CharField(choices=[('buyside swept', 'Buyside Swept'), ('sellside swept', 'Sellside Swept'), ('neither', 'Neither'), ('both', 'Both'), ('london lows swept', 'London Lows Swept')], max_length=50)),
                ('lower_tf_bos', models.CharField(max_length=50)),
                ('fvg_present', models.BooleanField(default=False)),
                ('ifvg', models.BooleanField(default=False)),
                ('retest_into_ob', models.BooleanField(default=False)),
                ('session_time', models.CharField(choices=[('Asian', 'Asian'), ('London', 'London'), ('NewYork', 'New York')], max_length=20)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('setup_present', models.BooleanField(default=False)),
                ('high_impact_news', models.CharField(blank=True, max_length=200)),
                ('entry_trigger', models.CharField(max_length=200)),
                ('behaviour_based_on_previous_moves', models.TextField()),
                ('outcome', models.CharField(choices=[('no_setup', 'No Setup'), ('win', 'Win'), ('loss', 'Loss')], max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='journal/backtesting/')),
                ('notes', models.TextField(blank=True)),
                ('chasing_long_on', models.BooleanField(default=False)),
                ('overnight', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Backtest Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreTradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('bias', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=10)),
                ('predicted_htf_direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=10)),
                ('market_condition', models.CharField(choices=[('Trending Up', 'Trending Up'), ('Trending Down', 'Trending Down'), ('Consolidating', 'Consolidating')], max_length=20)),
                ('liquidity_analysis', models.CharField(choices=[('buyside swept', 'Buyside Swept'), ('sellside swept', 'Sellside Swept'), ('neither', 'Neither'), ('both', 'Both'), ('london lows swept', 'London Lows Swept')], max_length=50)),
                ('htf_poi_type', models.CharField(max_length=100)),
                ('session_target', models.CharField(choices=[('Asian', 'Asian'), ('London', 'London'), ('NewYork', 'New York')], max_length=20)),
                ('htf_draws', models.TextField()),
                ('lower_tf_confirmation', models.TextField()),
                ('setup_image', models.ImageField(blank=True, null=True, upload_to='journal/pre_trade/')),
                ('all_conditions_met', models.BooleanField(default=False)),
                ('trade_taken', models.BooleanField(default=False)),
                ('reason_for_taking_or_not', models.TextField()),
                ('outcome_image', models.ImageField(blank=True, null=True, upload_to='journal/pre_trade_outcomes/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_trade_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pre Trade Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
