# Generated by Django 5.2 on 2025-11-01 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_aftertradeentry_backtestentry_pretradeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Strategy Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aftertradeentry',
            name='reward_pips',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Take profit in pips', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aftertradeentry',
            name='risk_pips',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stop loss in pips', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aftertradeentry',
            name='rr_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated Risk:Reward ratio', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='LotSizeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stop_loss_pips', models.DecimalField(decimal_places=2, max_digits=8)),
                ('instrument', models.CharField(max_length=20)),
                ('calculated_lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lot Size Calculations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aftertradeentry',
            name='strategy_tags',
            field=models.ManyToManyField(blank=True, related_name='after_trade_entries', to='journal.strategytag'),
        ),
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict, help_text='Stored filter parameters')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
