# Generated by Django 5.2 on 2025-11-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_strategytag_aftertradeentry_reward_pips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftertradeentry',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Auto-generated trade summary', null=True),
        ),
        migrations.AddField(
            model_name='aftertradeentry',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
