# Generated by Django 5.2 on 2025-11-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_aftertradeentry_ai_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name (e.g., session, market_condition)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name (e.g., Trading Session)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Choice Categories',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Value stored in database', max_length=100)),
                ('display_label', models.CharField(help_text='Label shown to users', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for badges (optional)', max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='journal.choicecategory')),
            ],
            options={
                'ordering': ['category__order', 'category__name', 'order', 'display_label'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
