# Generated by Django 5.2 on 2025-11-03 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_choicecategory_choiceoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMistakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('entry', 'Entry Mistakes'), ('exit', 'Exit Mistakes'), ('risk', 'Risk Management'), ('psychology', 'Psychology'), ('analysis', 'Market Analysis'), ('other', 'Other')], default='other', max_length=50)),
                ('frequency_count', models.IntegerField(default=1, help_text='How many times this mistake has been observed')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('suggested_solution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Common Mistake',
                'verbose_name_plural': 'Common Mistakes',
                'ordering': ['-frequency_count', '-created_at'],
            },
        ),
    ]
