# Generated by Django 5.2 on 2025-11-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_commonmistakelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicecategory',
            options={'ordering': ['journal_type', 'order', 'display_name'], 'verbose_name_plural': 'Choice Categories'},
        ),
        migrations.AddField(
            model_name='choicecategory',
            name='field_name',
            field=models.CharField(blank=True, help_text='Form field name to map this category to (e.g., session, bias). Leave blank for dynamic fields.', max_length=50),
        ),
        migrations.AddField(
            model_name='choicecategory',
            name='journal_type',
            field=models.CharField(choices=[('after_trade', 'After Trade'), ('pre_trade', 'Pre Trade'), ('backtest', 'Backtest'), ('all', 'All Journals')], default='all', help_text='Which journal type this category belongs to', max_length=20),
        ),
    ]
