# Generated by Django 5.2 on 2025-11-30 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_tradetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.CharField(choices=[('after_trade', 'After Trade'), ('pre_trade', 'Pre Trade'), ('backtest', 'Backtest')], max_length=20)),
                ('name', models.CharField(help_text='Field name (internal identifier, e.g., "smt_confirmation")', max_length=100)),
                ('display_name', models.CharField(help_text='Display name (e.g., "SMT Confirmation")', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('select', 'Select (Single Choice)'), ('multiselect', 'Multi-Select (Multiple Choices)'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('url', 'URL'), ('email', 'Email')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True, help_text='Help text shown to users')),
                ('default_value', models.TextField(blank=True, help_text='Default value for this field')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Field',
                'verbose_name_plural': 'Journal Fields',
                'ordering': ['journal_type', 'order', 'display_name'],
                'unique_together': {('user', 'journal_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JournalFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Value stored in database', max_length=200)),
                ('display_label', models.CharField(help_text='Label shown to users', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for badges', max_length=7)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='journal.journalfield')),
            ],
            options={
                'ordering': ['field', 'order', 'display_label'],
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.CreateModel(
            name='JournalFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('after_trade', 'After Trade'), ('pre_trade', 'Pre Trade'), ('backtest', 'Backtest')], max_length=20)),
                ('entry_id', models.IntegerField(help_text='ID of the journal entry')),
                ('value_text', models.TextField(blank=True, help_text='Stored as text, parsed by field type')),
                ('value_number', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='journal.journalfield')),
            ],
            options={
                'verbose_name': 'Journal Field Value',
                'verbose_name_plural': 'Journal Field Values',
                'ordering': ['field__order', 'field__display_name'],
                'unique_together': {('entry_type', 'entry_id', 'field')},
            },
        ),
    ]
