# Generated by Django 5.2 on 2025-11-30 09:37

import django.db.models.deletion
import journal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_journalfield_journalfieldoption_journalfieldvalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.AddField(
            model_name='lotsizecalculation',
            name='account_currency',
            field=models.CharField(default='USD', help_text='Account currency', max_length=10),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.get_after_trade_upload_path),
        ),
        migrations.AlterField(
            model_name='backtestentry',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.get_backtest_upload_path),
        ),
        migrations.AlterField(
            model_name='lotsizecalculation',
            name='instrument',
            field=models.CharField(help_text='Instrument name (e.g., EUR/USD)', max_length=100),
        ),
        migrations.AlterField(
            model_name='lotsizecalculation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_size_calculations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pretradeentry',
            name='outcome_image',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.get_pre_trade_outcome_upload_path),
        ),
        migrations.AlterField(
            model_name='pretradeentry',
            name='setup_image',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.get_pre_trade_upload_path),
        ),
        migrations.AddIndex(
            model_name='lotsizecalculation',
            index=models.Index(fields=['user', '-created_at'], name='journal_lot_user_id_44475e_idx'),
        ),
        # Add account_currency to LotSizeCalculation
        migrations.AddField(
            model_name='lotsizecalculation',
            name='account_currency',
            field=models.CharField(default='USD', help_text='Account currency', max_length=10),
        ),
        # Update instrument field to allow longer names
        migrations.AlterField(
            model_name='lotsizecalculation',
            name='instrument',
            field=models.CharField(help_text='Instrument name (e.g., EUR/USD)', max_length=100),
        ),
        # Remove Entry model (legacy, unused)
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
