# Generated by Django 5.2 on 2025-11-30 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_remove_entry_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftertradeentry',
            name='bias',
            field=models.CharField(blank=True, choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='discipline_score',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very poor', 'Very Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='entry_quality',
            field=models.CharField(blank=True, choices=[('perfect', 'Perfect'), ('chased', 'Chased'), ('early', 'Early'), ('late', 'Late'), ('stop loss issue', 'Stop Loss Issue')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='liquidity_analysis',
            field=models.CharField(blank=True, choices=[('buyside swept', 'Buyside Swept'), ('sellside swept', 'Sellside Swept'), ('neither', 'Neither'), ('both', 'Both'), ('london lows swept', 'London Lows Swept')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='lower_tf_confirmation',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='market_behaviour',
            field=models.CharField(blank=True, choices=[('as expected', 'As Expected'), ('choppy', 'Choppy'), ('surprise', 'Surprise'), ('opposite', 'Opposite'), ('hit stop then reversed', 'Hit Stop Then Reversed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='market_condition',
            field=models.CharField(blank=True, choices=[('Trending Up', 'Trending Up'), ('Trending Down', 'Trending Down'), ('Consolidating', 'Consolidating')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='poi_performance',
            field=models.CharField(blank=True, choices=[('respected perfectly', 'Respected Perfectly'), ('overshot', 'Overshot'), ('partial fill', 'Partial Fill'), ('no htf poi', 'No HTF POI'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='poi_quality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='predicted_directional_bias',
            field=models.CharField(blank=True, choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partial', 'Partial')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='risk_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='session',
            field=models.CharField(blank=True, choices=[('Asian', 'Asian'), ('London', 'London'), ('NewYork', 'New York')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aftertradeentry',
            name='time_of_entry',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
